name: CI
on:
  pull_request: {}
  push:
    branches: [main]

jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          SOURCE: media-source-respec.html
          DESTINATION: index.html
          GH_PAGES_BRANCH: gh-pages
